apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: backend-dev
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: TU_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: TU_SECRET_KEY
  AWS_DEFAULT_REGION: us-east-1
